tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#dbfcff",
        "tertiary-container": "#71717a",
        "on-tertiary-fixed": "#18181b",
        "electric-cyan": "#00F0FF",
        "cyan-accent": "#00F0FF",
        "primary-fixed-dim": "#00dbe9",
        "surface-navy": "#111827",
        "on-surface-variant": "#b9cacb",
        "tertiary-fixed-dim": "#a1a1aa",
        "obsidian-base": "#050608",
        "on-surface": "#e2e2e8",
        "primary-container": "#00f0ff",
        "primary-fixed": "#7df4ff",
        "on-primary-fixed": "#002022",
        background: "#111318",
        "on-tertiary-container": "#d4d4d8",
        outline: "#849495",
        surface: "#111318",
        "surface-dim": "#111318",
        error: "#ffb4ab",
        "on-error": "#690005",
        "surface-tint": "#00dbe9",
        "surface-bright": "#37393e",
        "security-gray": "#9CA3AF",
        "surface-container-highest": "#333539",
        "surface-container-lowest": "#0c0e12",
        tertiary: "#71717a",
        "slate-grey": "#71717a",
        "inverse-primary": "#006970",
        "on-error-container": "#ffdad6",
        "on-primary": "#00363a",
        "on-tertiary-fixed-variant": "#3f3f46",
        "tertiary-fixed": "#e4e4e7",
        "on-primary-container": "#006970",
        "surface-variant": "#333539",
        "inverse-surface": "#e2e2e8",
        "error-container": "#93000a",
        "inverse-on-surface": "#2f3035",
        "outline-variant": "#3b494b",
        "surface-container-high": "#282a2e",
        "on-primary-fixed-variant": "#004f54",
        "surface-container": "#1e2024",
        "on-tertiary": "#ffffff",
        "on-background": "#e2e2e8",
        "surface-container-low": "#1a1c20",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "container-max": "1440px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        margin: "48px",
        gutter: "24px",
        sm: "8px",
        md: "16px",
        lg: "32px",
        xl: "40px",
      },
      fontFamily: {
        "headline-md": ["Sora"],
        "label-md": ["JetBrains Mono"],
        "headline-lg": ["Sora"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Sora"],
        "headline-xl": ["Sora"],
        "body-lg": ["Inter"],
        "label-sm": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
      },
    },
  },
};
